server:
  port: 8500
  servlet:
    context-path: /

openai-service:
  api-key: ################
  gpt-model: gpt-3.5-turbo
  audio-model: whisper-1
  http-client:
    read-timeout: 3000
    connect-timeout: 3000
  urls:
    base-url: https://api.openai.com/v1
    chat-url: /chat/completions
    create-transcription-url: /audio/transcriptions

logging:
  level:
    com.github.wenqiglantz.service.openaiclient: TRACE

# Spring
spring:
  jackson:
    default-property-inclusion: NON_NULL
  cloud:
    openfeign:
      client:
        config:
          openai-service:
            connectTimeout: 160000
            readTimeout: 160000

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: 'ALWAYS'
  health:
    circuitbreakers:
      enabled: true
